First_django_project/First_app/urls.py
from django.urls import path
from First_app import views

app_name = "First_app"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('musician_details/<pk>/', views.MusicianDetails.as_view(), name='musician_details'),
    path('add_musician/', views.AddMusician.as_view(), name='add_musician'),
    path('musician_update/<pk>/', views.UpdateMusician.as_view(), name='musician_update'),
    path('musician_delete/<pk>/', views.DeleteMusician.as_view(), name='musician_delete'),
    
]

First_django_project/First_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('First_app.urls'))
]

First_django_project/First_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Musician(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="First name",)
    last_name = models.CharField(max_length=50, verbose_name="Last name",)
    instrument = models.CharField(max_length=50, verbose_name="Instrument",)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('First_app:musician_details', kwargs={'pk':self.pk})

class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE, related_name='album_list')  # models.Cascade If an album is here it won't let that musician to be deleted
    name = models.CharField(max_length=100, verbose_name="Album name",)
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Average"),
        (4, "Good"),
        (5, "Excellent")
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

First_django_project/First_app/forms.py
from django import forms
from First_app.models import Musician, Album

class MusicianForm(forms.ModelForm):
    class Meta:
        model = Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = Album
        fields = "__all__"

First_django_project/First_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView,  CreateView, UpdateView, DeleteView
from First_app import models
from django.urls import reverse_lazy

def index_test(request):
    return HttpResponse('Hello World')

class IndexView(ListView):
   context_object_name = 'musician_list'
   model = models.Musician
   template_name = 'First_app/index.html'

class MusicianDetails(DetailView):
    context_object_name = 'musician'
    model = models.Musician
    template_name = 'First_app/musician_details.html'

class AddMusician(CreateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'First_app/musician_form.html'

class UpdateMusician(UpdateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'First_app/musician_form.html'

class DeleteMusician(DeleteView):
    context_object_name = 'musician'
    model = models.Musician
    success_url = reverse_lazy('First_app:index')
    template_name = 'First_app/delete_musician.html'

First_django_project/First_app/templates/First_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudfare.com/ajax/libs/proper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrap.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'First_app:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'First_app:add_musician' %}">Add Musician</a>
            </li>
        </ul>
    </nav>
    <div class="container" style="padding-top:20px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

First_django_project/First_app/templates/First_app/delete_musician.html
{% extends 'First_app/base.html' %}
{% block body_block %}
<h3>Delete {{ musician.first_name }} {{ musician.last_name }}?</h3>
<form method="POST">
    {% csrf_token %}
    <input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm">
    <br>
    <a href="{% url 'First_app:musician_details' pk=musician.pk %}" class="btn btn-info btn-sm">Cancel</a>
</form>
{% endblock %}

First_django_project/First_app/templates/First_app/index.html
{% extends 'First_app/base.html' %}
{% block body_block %}
<ul>
    {% for musician in musician_list %}
    <li><a href="{% url 'First_app:musician_details' pk=musician.pk %}">{{ musician.first_name }} {{ musician.last_name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

First_django_project/First_app/templates/First_app/musician_details.html
{% extends 'First_app/base.html' %}
{% block body_block %}
<h3>Musician Details:</h3>
<p>{{ musician.first_name }} {{ musician.last_name }}</p>
<p>{{ musician.instrument }}</p>
<h3>Albums:</h3>
<ul>
    {% for album in musician.album_list.all %}
    <li>{{ album.name }}</li>
    {% endfor %}
</ul>
<a href="{% url 'First_app:musician_update' pk=musician.pk %}" class="btn btn-warning btn-sm">Update</a>
<a href="{% url 'First_app:musician_delete' pk=musician.pk %}" class="btn btn-danger btn-sm">Delete</a>
{% endblock %}

First_django_project/First_app/templates/First_app/musician_form.html
{% extends 'First_app/base.html' %}
{% block body_block %}
{% if form.instance.pk %}
<h3>Update Musician</h3>
{% else %}
<h3>Add New Musician</h3>
{% endif %}
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}