My_Blog_Project/App_Blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    re_path(r'^details/(?P<slug>.+)/$', views.blog_details, name='blog_details'),
    path('like/<pk>/', views.like, name='like_post'),
    path('unlike/<pk>/', views.unlike, name='unlike_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('update/<pk>', views.UpdateBlog.as_view(), name='update_blog'),
    

]

My_Blog_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('password/', views.change_pass, name='change_pass'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic')
]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog_Project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><img src="/media/home.png" width="50px"></a>
            </li>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    @{{ user.username }}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
                    <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
                    <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
                    <hr>
                    <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container" style="padding-top:20px">
        {% block body_block %}
        
        {% endblock %}
    </div>
</body>
</html>