My_Blog_Project/App_Blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    re_path(r'^details/(?P<slug>.+)/$', views.blog_details, name='blog_details'),
    path('like/<pk>/', views.like, name='like_post'),
    path('unlike/<pk>/', views.unlike, name='unlike_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('update/<pk>', views.UpdateBlog.as_view(), name='update_blog'),
    

]

My_Blog_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('password/', views.change_pass, name='change_pass'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic')
]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog_Project/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

My_Blog_Project/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email Address', required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

My_Blog_Project/App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'form':form, 'registered':registered}
    return render(request, 'App_Login/sign_up.html', context=dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})

@login_required
def update_profile(request):
    updated = False
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            updated = True
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/update_profile.html', context={'form':form, 'updated':updated})

@login_required
def change_pass(request):
    changed = False
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/change_pass.html', context={'form':form, 'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/update_pro_pic.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/update_pro_pic.html', context={'form':form})

My_Blog_Project/templates/App_Login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_blok %} Change Password {% endblock %}
{% block body_block %}
{% if changed %}
<div class="alert alert-success">Password Changed Successfully</div>
{% endif %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-info btn-sm">Update</button>
</form>
{% endblock %}

My_Blog_Project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_blok %} Login {% endblock %}
{% block body_block %}
<h2>Login:</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>
{% endblock %}

My_Blog_Project/templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
<h1>Your Profile</h1>
{% if user.user_profile %}
<img src="/media/{{ user.user_profile.profile_pic }}" class="rounded-cirle" width="100px">
<br>
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-primary btn-sm">Change Profile Picture</a>
{% else %}
<img src="/media/profile_pics/avatar_male.png" class="rounded-cirle" width="100px">
<br>
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-primary btn-sm">Upload Profile Picture</a>
{% endif %}
<br>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }} </p>
<br>
<a href="{% url 'App_Login:update_profile' %}" class="btn btn-warning btn-sm">Update profile</a>
<a href="{% url 'App_Login:change_pass' %}" class="btn btn-warning btn-sm">Change Password</a>

{% endblock %}

My_Blog_Project/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} Create New Account {% endblock %}
{% block body_block %}
{% if registered %}
    <div class="alert alert-success ">
        Account Created Successfully! 
        <a href="{% url 'App_Login:login' %}">Login Here!</a>
    </div>
{% else %}
    <h2>Create New Account</h2>
    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Create Account</button>
    </form>
    <br>
    <p>Already have an account?<a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endif %}
{% endblock %}

My_Blog_Project/templates/App_Login/update_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
<h2>Add Your Profile Picture:</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add Picture</button>
</form>
{% endblock %}

My_Blog_Project/templates/App_Login/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_blok %} Change Profile {% endblock %}
{% block body_block %}
{% if updated %}
<div class="alert alert-success">Profile Updated Successfully</div>
{% endif %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-info btn-sm">Update</button>
</form>
{% endblock %}